
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: developer
  password: devonly
  database: testing

test:
  <<: *default
  username: testing
  password: testing
  database: testing

#production:
#  <<: *default
#  database: UsersAndStats_production
#  username: UsersAndStats
#  password: <%= ENV['USERSANDSTATS_DATABASE_PASSWORD'] %>
