
default: &default
  adapter: mysql2
  username: db_tester
  pool: 5

development:
  <<: *default
  database: UsersAndStatsDev

test:
  <<: *default
  database: UsersAndStatsTest

#production:
#  <<: *default
#  database: UsersAndStats_production
#  username: UsersAndStats
#  password: <%= ENV['USERSANDSTATS_DATABASE_PASSWORD'] %>
